micronaut:
  application:
    name: jdbc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/dbtest
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
